<?php

return $products = [
  //prodotti ristorante id=1 (da id 1 a id 13)
  [
    "restaurant_id" => 1,
    "name" => "Marinara",
    "slug" => "marinara",
    "image" => "",
    "description" => "pomodoro, aglio e origano",
    "price" => 3.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita",
    "slug" => "margherita",
    "image" => "",
    "description" => "pomodoro e mozzarella",
    "price" => 4.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita con funghi",
    "slug" => "margherita-con-funghi",
    "image" => "",
    "description" => "pomodoro, mozzarella e funghi champignon",
    "price" => 5.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Crostino",
    "slug" => "crostino",
    "image" => "",
    "description" => "mozzarella e prosciutto cotto",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Napoli",
    "slug" => "napoli",
    "image" => "",
    "description" => "pomodoro, mozzarella e filetti di alici",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Diavola",
    "slug" => "diavola",
    "image" => "",
    "description" => "pomodoro, mozzarella e ventricina",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Boscaiola",
    "slug" => "bianca-boscaiola",
    "image" => "",
    "description" => "mozzarella, funghi champignon e salsiccia di Norcia",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca ai 4 Formaggi",
    "slug" => "bianca-ai-4-formaggi",
    "image" => "",
    "description" => "mozzarella, gorgonzola DOP, provola affumicata e grana DOP",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Ortolana",
    "slug" => "bianca-ortolana",
    "image" => "",
    "description" => "mozzarella, funghi champignon, zucchine e melanzane grigliate",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Capricciosa",
    "slug" => "capricciosa",
    "image" => "",
    "description" => "pomodoro, mozzarella, carciofini, olive nere, funghi champignon, uovo sodo e prosciutto crudo",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita Amatriciana",
    "slug" => "margherita-amatriciana",
    "image" => "",
    "description" => "pomodoro, mozzarella, pancetta e pecorino",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì con Cacio e Pepe Artigianal",
    "slug" => "supplì-con-cacio-e-pepe-artigianal",
    "image" => "",
    "description" => "più leggero e croccante con farina di mais",
    "price" => 1.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì Chic",
    "slug" => "supplì-chic",
    "image" => "",
    "description" => "bianco con mozzarella e tartufo nero di norcia nuovo",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=2 (da id 14 a id 28)
  [
    "restaurant_id" => 2,
    "name" => "Sushi Bento 12 Pezzi",
    "slug" => "sushi-bento-12-pezzi",
    "image" => "",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco, 4 uramaki california e 4 hosomaki salmone",
    "price" => 11.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Nigiri Sho 6 Pezzi",
    "slug" => "nigiri-sho-6-pezzi",
    "image" => "",
    "description" => "3 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco e 1 nigiri tonno",
    "price" => 8.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Sho 10 Pezzi",
    "slug" => "sushi-sho-10-pezzi",
    "image" => "",
    "description" => "10 nigiri sake",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Special 14 Pezzi",
    "slug" => "sushi-special-14-pezzi",
    "image" => "",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 2 nigiri pesce bianco, 1 nigiri tonno, 4 hosomaki salmone e 4 hosomaki avocado",
    "price" => 12.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Chanel Tris di Pesce",
    "slug" => "chanel-tris-di-pesce",
    "image" => "",
    "description" => "riso sushi, salmone, tonno, spigola, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pukas Salmone Grill",
    "slug" => "pukas-salmone-grill",
    "image" => "",
    "description" => "riso sushi, salmone grigliato, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Emmery Tonno",
    "slug" => "emmery-tonno",
    "image" => "",
    "description" => "riso sushi, tonno, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Kauai Spigola",
    "slug" => "kauai-spigola",
    "image" => "",
    "description" => "iso sushi, spigola, avocado, carote, edamame, finocchio, insalata di misticanza, mais, mango, pomodorini, radicchio e semi di sesamo",
    "price" => 13.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Involtini Primavera",
    "slug" => "involtini-primavera",
    "image" => "",
    "description" => "verza bianca e carote freshly homemade, 3 pezzi",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Carne al Vapore",
    "slug" => "ravioli-di-carne-al-vapore",
    "image" => "",
    "description" => "verza bianca e carne di maiale, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Onion Rings",
    "slug" => "onion-rings",
    "image" => "",
    "description" => "croccanti anelli di cipolla fritti tipici della cucina americana, 8 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure al Vapore",
    "slug" => "ravioli-di-verdure-al-vapore",
    "image" => "",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure alla Griglia",
    "slug" => "ravioli-di-verdure-alla-griglia",
    "image" => "",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 4.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai di Pollo",
    "slug" => "pad-thai-di-pollo",
    "image" => "",
    "description" => "tagliatelle di riso thailandese, carote, verza bianca, zucchine, uova, pollo fritto croccante, salsa thailandese, salsa teriyaki condito con granella di noccioline tostate e lime",
    "price" => 8.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai Frutti di Mare",
    "slug" => "pad-thai-frutti-di-mare",
    "image" => "",
    "description" => "tagliatelle di riso tailandesi, carote, verza bianca, zucchine, uova, gamberi, polpa di granchio, calamari, salsa thailandese ,salsa teriyaki condita con granella di noccioline tostate, salsa teriyaki e lime",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
];
