<?php

return $products = [
  //prodotti ristorante id=1 (da id 1 a id 13)
  [
    "restaurant_id" => 1,
    "name" => "Marinara",
    "image" => "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/vimdb/83535_751-0-4864-4864.jpg",
    "slug" => "marinara",
    "description" => "pomodoro, aglio e origano",
    "price" => 3.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita",
    "slug" => "margherita",
    "image" => "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg",
    "description" => "pizza pomodoro e mozzarella",
    "price" => 4.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita con funghi",
    "slug" => "margherita-con-funghi",
    "image" => "https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2019/10/4102_Pizza.jpg?resize=895%2C616&ssl=1",
    "description" => "pomodoro, mozzarella e funghi champignon",
    "price" => 5.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Crostino",
    "slug" => "crostino",
    "image" => "https://www.lacucinaimperfetta.com/wp-content/uploads/2014/09/Focaccia-prosciutto-e-formaggio.jpg",
    "description" => "mozzarella e prosciutto cotto",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Napoli",
    "slug" => "napoli",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/07/pizza-napoli-5.jpg",
    "description" => "pomodoro, mozzarella e filetti di alici",
    "price" => 5.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Diavola",
    "slug" => "diavola",
    "image" => "https://www.cucinare.it/uploads/wp-content/uploads/2015/10/ricetta_pizza_alla_diavola.jpg",
    "description" => "pomodoro, mozzarella e ventricina",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Boscaiola",
    "slug" => "bianca-boscaiola",
    "image" => "https://i.ytimg.com/vi/SwPvqV_qCCA/maxresdefault.jpg",
    "description" => "mozzarella, funghi champignon e salsiccia di Norcia",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca ai 4 Formaggi",
    "slug" => "bianca-ai-4-formaggi",
    "image" => "https://wips.plug.it/cips/buonissimo.org/cms/2012/12/10798952_l.jpg",
    "description" => "mozzarella, gorgonzola DOP, provola affumicata e grana DOP",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Bianca Ortolana",
    "slug" => "bianca-ortolana",
    "image" => "https://www.granarolo.it/system/granarolo_consumer/attachments/data/000/001/792/original/pizza-ortolana.jpg?1490627997",
    "description" => "mozzarella, funghi champignon, zucchine e melanzane grigliate",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Capricciosa",
    "slug" => "capricciosa",
    "image" => "https://i2.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/12/3240_Pizza.jpg?resize=895%2C616&ssl=1",
    "description" => "pomodoro, mozzarella, carciofini, olive nere, funghi champignon, uovo sodo e prosciutto crudo",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Margherita Amatriciana",
    "slug" => "margherita-amatriciana",
    "image" => "https://www.pizzainncasa.com/wp-content/uploads/2019/01/pizza-all-Amatriciana-1.jpg",
    "description" => "pomodoro, mozzarella, pancetta e pecorino",
    "price" => 6.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì con Cacio e Pepe Artigianal",
    "slug" => "supplì-con-cacio-e-pepe-artigianal",
    "image" => "https://moondo.info/wp-content/uploads/2018/05/suppl%C3%AC-cacio-e-pepe.jpg",
    "description" => "più leggero e croccante con farina di mais",
    "price" => 1.80,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 1,
    "name" => "Supplì Chic",
    "slug" => "supplì-chic",
    "image" => "https://www.italiachiamaitalia.it/wp-content/uploads/2016/08/28683-suppli.gif",
    "description" => "bianco con mozzarella e tartufo nero di norcia nuovo",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=2 (da id 14 a id 28)
  [
    "restaurant_id" => 2,
    "name" => "Sushi Bento 12 Pezzi",
    "slug" => "sushi-bento-12-pezzi",
    "image" => "",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco, 4 uramaki california e 4 hosomaki salmone",
    "price" => 11.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Nigiri Sho 6 Pezzi",
    "slug" => "nigiri-sho-6-pezzi",
    "image" => "",
    "description" => "3 nigiri salmone, 1 nigiri gambero reale, 1 nigiri pesce bianco e 1 nigiri tonno",
    "price" => 8.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Sho 10 Pezzi",
    "slug" => "sushi-sho-10-pezzi",
    "image" => "",
    "description" => "10 nigiri sake",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Sushi Special 14 Pezzi",
    "slug" => "sushi-special-14-pezzi",
    "image" => "",
    "description" => "2 nigiri salmone, 1 nigiri gambero reale, 2 nigiri pesce bianco, 1 nigiri tonno, 4 hosomaki salmone e 4 hosomaki avocado",
    "price" => 12.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Chanel Tris di Pesce",
    "slug" => "chanel-tris-di-pesce",
    "image" => "",
    "description" => "riso sushi, salmone, tonno, spigola, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 14.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pukas Salmone Grill",
    "slug" => "pukas-salmone-grill",
    "image" => "",
    "description" => "riso sushi, salmone grigliato, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Emmery Tonno",
    "slug" => "emmery-tonno",
    "image" => "",
    "description" => "riso sushi, tonno, avocado, cipolla fritta croccante, edamame, finocchio, mango, radicchio, tobiko, wakame e semi di sesamo",
    "price" => 13.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Kauai Spigola",
    "slug" => "kauai-spigola",
    "image" => "",
    "description" => "iso sushi, spigola, avocado, carote, edamame, finocchio, insalata di misticanza, mais, mango, pomodorini, radicchio e semi di sesamo",
    "price" => 13.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Involtini Primavera",
    "slug" => "involtini-primavera",
    "image" => "",
    "description" => "verza bianca e carote freshly homemade, 3 pezzi",
    "price" => 2.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Carne al Vapore",
    "slug" => "ravioli-di-carne-al-vapore",
    "image" => "",
    "description" => "verza bianca e carne di maiale, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Onion Rings",
    "slug" => "onion-rings",
    "image" => "",
    "description" => "croccanti anelli di cipolla fritti tipici della cucina americana, 8 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure al Vapore",
    "slug" => "ravioli-di-verdure-al-vapore",
    "image" => "",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 3.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Ravioli di Verdure alla Griglia",
    "slug" => "ravioli-di-verdure-alla-griglia",
    "image" => "",
    "description" => "farina di grano, acqua, verza, sale, olio d'oliva, carota cinese e spinaci, 4 pezzi",
    "price" => 4.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai di Pollo",
    "slug" => "pad-thai-di-pollo",
    "image" => "",
    "description" => "tagliatelle di riso thailandese, carote, verza bianca, zucchine, uova, pollo fritto croccante, salsa thailandese, salsa teriyaki condito con granella di noccioline tostate e lime",
    "price" => 8.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 2,
    "name" => "Pad Thai Frutti di Mare",
    "slug" => "pad-thai-frutti-di-mare",
    "image" => "",
    "description" => "tagliatelle di riso tailandesi, carote, verza bianca, zucchine, uova, gamberi, polpa di granchio, calamari, salsa thailandese ,salsa teriyaki condita con granella di noccioline tostate, salsa teriyaki e lime",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  //prodotti ristorante id=3 (da id 29 a id 34)
  [
    "restaurant_id" => 3,
    "name" => "Genovese di Tonno",
    "slug" => "genovese-di-tonno",
    "image" => "",
    "description" => "tonno fresco scottato in padella, crema di cipolla, battuto di prezzemolo a scelta e cacio ricotta a scelta",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Orecchiette ragù",
    "slug" => "orecchiette-ragù",
    "image" => "",
    "description" => "ragù di manzo italiano e cacioricotta a scelta",
    "price" => 9.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Orecchiette Cime di Rapa",
    "slug" => "orecchiette-cime-di-rapa",
    "image" => "",
    "description" => "cime di rapa, olio extravergine d'oliva e battuto di alici a scelta",
    "price" => 8.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pomodori Scattarisciati",
    "slug" => "pomodori-scattarisciati",
    "image" => "",
    "description" => "pomodoro fresco soffritto, peperone cornetto e basilico",
    "price" => 5.50,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pasticciotti Crema Classica",
    "slug" => "pasticciotti-crema-classica",
    "image" => "",
    "description" => "pasta frolla e crema pasticcera",
    "price" => 2.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 3,
    "name" => "Pasticciotti Pistacchio",
    "slug" => "pasticciotti-pistacchio",
    "image" => "",
    "description" => "pastra frolla con granella di pistacchio e crema ai pistacchi",
    "price" => 2.20,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  //prodotti ristorante id=4 (da id 35 a id 41)
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Pantera Rosa",
    "slug" => "pagnottella-pantera-rosa",
    "image" => "https://www.fabiobarbatopersonalchef.com/wp-content/uploads/2016/07/Pagnottelle-rustiche-2.jpg",
    "description" => "prosciutto cotto, pomodoro a fette, insalata e salsa rosa",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Friarielli Vivo",
    "slug" => "pagnottella-friarielli-vivo",
    "image" => "https://www.cucinasud.it/images/2020/01/23/babasasicce_large.jpg",
    "description" => "salsiccia, provola affumicata e friarielli",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella al Volo",
    "slug" => "pagnottella-al-volo",
    "image" => "https://www.tutored.me/it/wp-content/uploads/sites/13/2016/10/pantelleria_homepage-e1476436647609.jpg",
    "description" => "tonno, pomodoro a fette, insalata e salsa rosa",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Pagnottella Pesto, Caprino e Pomodori Secchi",
    "slug" => "pagnottella-pesto-caprino-e-pomodori-secchi",
    "image" => "https://2.bp.blogspot.com/_lmT8xlMCBaM/TNO1dtyz8UI/AAAAAAAAAic/tJ84DqLcYyA/w1200-h630-p-k-no-nu/cestini+salsiccia+radicchio+caprino2-2.jpg",
    "description" => "mozzarella , pesto , caprino e pomodori secchi",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Le Ripiene Pizza Romana",
    "slug" => "le-ripiene-pizza-romana",
    "image" => "https://www.scattidigusto.it/wp-content/uploads/2013/07/fazzoletto-parmigiana-melanzane-Gabriele-Bonci-32.jpg",
    "description" => "mortadella, salsa tartufata e mozzarella",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Parmense",
    "slug" => "parmense",
    "image" => "https://i.pinimg.com/originals/98/52/5e/98525e7f89ff82fc1fb3da293b7bc962.jpg",
    "description" => "rughetta, pomodorini, prosciutto crudo e mozzarella",
    "price" => 6.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 4,
    "name" => "Focaccia Vegetariana",
    "slug" => "focaccia-vegetariana",
    "image" => "https://www.ristorazioneitalianamagazine.it/CMS/wp-content/uploads/2018/02/04-Pizza-con-la-cicoria-1.jpg",
    "description" => "mozzarella, peperoni, melanzane e zucchine",
    "price" => 7.00,
    "is_vegetarian" => 1,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 5,
    "name" => "Fusilli di Mais",
    "slug" => "fusilli-di-mais",
    "image" => "https://www.lospicchiodaglio.it/img/ricette/pastaspeckradicchio.jpg",
    "description" => "Fusilli di Mais e Riso con Speck e Zafferanoe",
    "price" => 8.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],
  [
    "restaurant_id" => 5,
    "name" => "Lasagna",
    "slug" => "lasagna",
    "image" => "https://www.smeg.com/binaries/content/gallery/smeg-italy/news/8-lasagne-bolo.jpg/8-lasagne-bolo.jpg/brx%3ApostcardDeskLarge",
    "description" => "Lasagna alla Bolognese, con spalla di manzo",
    "price" => 6.00,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 6,
    "name" => "Burrito con Chili",
    "slug" => "burrito-con-chili",
    "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2018/03/burrito-di-carne/jcr:content/header-par/image-single.img10.jpg/1521454018401.jpg",
    "description" => "chili con carne di nostra produzione, riso, insalata, salsa guacamole, salsa ranch, panna acida e jalapeno a fette",
    "price" => 7.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 6,
    "name" => "Burrito Picadillo",
    "slug" => "fajitas-picadillo",
    "image" => "https://i.pinimg.com/originals/9e/39/14/9e3914115af65f7c5d859124fc880d79.jpg",
    "description" => "carne di manzo con polpa di pomodoro, peperoni a striscioline e jalapeno, insalata, riso, panna acida e salsa ranch",
    "price" => 7.50,
    "is_vegetarian" => 0,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 7,
    "name" => "Chatpatta Allo",
    "slug" => "chatpatta-alloo",
    "image" => "https://i0.wp.com/www.curryandvanilla.com/wp-content/uploads/2018/11/chatpata-aloo-tuk-d.jpg?resize=600%2C629&ssl=1",
    "description" => "patate salate in salsa di menta e coriandolo",
    "price" => 5,
    "is_vegetarian" => 1,
    "is_glutenfree" => 0,
  ],
  [
    "restaurant_id" => 7,
    "name" => "Tandoori Chicken Senza Glutine",
    "slug" => "Tandoori-chicken-senza-glutine",
    "image" => "https://spicecravings.com/wp-content/uploads/2020/12/Tandoori-Chicken-Wings-featured-1.jpg",
    "description" => "cosce di pollo marinate e cotte al tandoori",
    "price" => 7,
    "is_vegetarian" => 0,
    "is_glutenfree" => 1,
  ],

];
